[project]
name = "cog-flex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno>=2.0.2",
    "google-genai>=1.35.0",
    "rich>=14.1.0",
]
